Repository RisingLight/Project-Euler, pull requests merged in 2019-10, with the labels that each got.

#10 4 and 16 solved
  Python/16. Power digit sum/PowerDigitSum.py
  Python/4. Largest palindrome product/palindrome_number.py
Labels: All Correct

#12 "Added new python scripts (04. Largest palindrome product)"
  Python/1. Multiples of 3 and 5/multiples_3_and_5.py
  Python/4. Largest palindrome product/largest_palin_product.py
  Python/5. Smallest multiple/smallest_multi.py
Labels: Partly Correct

#77 Added Solution for Prob4 in CPP
  CPP/04.Largest_palindrome_product/pranshu2610.cpp
  README.md
Labels: All Correct

#78 Problem7 in python
  Python/7.10001st_prime/SanchiMittal.py
  README.md
Labels: All Correct

#84 Added a C program for Even_fibonacci_numbers and updated README.md
  C/Even_fibonacci_numbers/Kavya-Shekar.c
  README.md
Labels: All Correct

#82 adding 13th problem in python
  Python/13. Large sum/jac08h.py
  README.md
Labels: All Correct, Re-Check-GuideLines

#88 Prob28 cpp
  CPP/04.Largest_palindrome_product/pranshu2610.cpp
  CPP/28.Number_spiral_diagonal/pranshu2610.cpp
  README.md
Labels: All Correct

#89 C and Py solution for Problem 28
  C/28.Number_spiral_diagonal/pranshu2610.c
  Python/28.Number_spiral_diagonal/pranshu2610.py
  README.md
Labels: All Correct

#71 Add C solution for problem 2.
  C/2. Even Fibonacci numbers/even_fibonacci.c
Labels: All Correct

#74 Solutions in Python [20 28 29 30 50] and R [1]
  Python/20.Factorial digit sum/said3427.py
  Python/28. Number spiral diagonals/said3427.py
  Python/29. Distinct powers/said3427.py
  Python/30. Digit fifth powers/said3427.py
  Python/50. Consecutive prime sum/said3427.py
  R/1. Multiples of 3 and 5/said3427.R
  README.md
Labels: All Correct

#44 25 done in Python
  Python/25.1000-digit_Fibonacci_number/RodolfoFerro.py
  README.md
Labels: All Correct

#95 Problem 50 in C
  C/50.Consecutive_prime_sum/ValentinDSJ.c
  README.md
Labels: All Correct

#103 03 done in C
  C/03.Largest_prime_factor/AxelMathei.c
  README.md
Labels: All Correct

#93 Added Integer Right Triangles for cpp
  CPP/39.Integer_Right_Triangles/mfarukkoc.cpp
  README.md
Labels: All Correct

#105 06 done in C
  C/06.Sum_square_difference/AxelMathei.c
  README.md
Labels: All Correct

#58 Largest Prime Factor solution in Dart
  Dart/03.largestPrimeFactor/akarshsingh9.dart
  README.md
Labels: Re-Check-GuideLines, Resolve Conflict

#99 Problem 10 done in C langauge
  C/10. Summation_of_primes/Kavya-Shekar.c
  README.md
Labels: All Correct

#114 Euler 2 done in R. Euler 47 and 49 done in Py3
  Python/47.Distinct primes factors/said3427.py
  Python/49.Prime permutations/said3427.py
  R/2.Even Fibonacci numbers/said3427.R
  README.md
Labels: Partly Correct

#115 07 done in C
  C/07.10001st_prime/AxelMathei.c
  README.md
Labels: All Correct

#121 Problem 50 done in go
  Go Lang/50.Consecutive_prime_sum/ValentinDSJ.go
  README.md
Labels: All Correct

#120 11 done in C
  C/11.Largest_product_in_a_grid/AxelMathei.c
  README.md
Labels: All Correct

#107 Problem 22 done in Python
  Python/22.names_scores/Vipul-Bajaj.py
  README.md
Labels: All Correct

#122 12 done in C
  C/12.Highly_divisible_triangular_number/AxelMathei.c
  README.md
Labels: All Correct

#118 Exercise 28 in Java language added
  Java/28.Number spiral diagonals/danmoren.java
  README.md
Labels: All Correct

#87 10 done in Python
  Python/10. Summation of primes/Artyko.py
  README.md
Labels: All Correct

#117 Exercise 31 in Java language added
  Java/31.Coin sums/danmoren.java
Labels: All Correct

#124 problem_40 done in Python
  Python/40. Champernowne's constant/walkerdea.py
  README.md
Labels: All Correct

#129 Problem 35 done in Python 3
  Python/35. Circular Prime/av.arvind77.py
  README.md
Labels: All Correct

#131 Problem 44 done in Python 3
  Python/44. Pentagon Numbers/av-arvind77.py
  README.md
Labels: All Correct

#132 Problem 11 done in Python 3
  Python/11. Largest Product in Grid/av-arvind77.py
  Python/11. Largest Product in Grid/euler11.txt
  README.md
Labels: All Correct

#135 problem 16 done in Java
  Java/16.Power Digit Sum/pragyanmehrotra.java
  README.md
Labels: All Correct

#36 Problem 13 in python
  Python/13. Large sum/ramonssarmento.py
  README.md
Labels: All Correct

#141 17 solved in Python 3
  Python/17.Number_letter_counts/prajwal-naik.py
  README.md
Labels: All Correct

#139 Problem 6 done in Java
  Java/6.Sum Square Difference/pragyanmehrotra.java
  README.md
Labels: All Correct

#138 Problem 20 solved in Java
  Java/20.Factorial Digit Sum/pragyanmehrotra.java
  README.md
Labels: All Correct

#134 12 done in Py3
  Python/12. Highly_divisible_triangular_number/ankitRai96.py
  README.md
Labels: All Correct

#146 1 solved in Ruby.
  README.md
  Ruby/01.Multiples of 3 and 5/24sharkS.rb
Labels: All Correct, Re-Check-GuideLines

#148 Euler 45 and 46 done in Py3
  Python/45.Triangular, pentagonal, and hexagonal/said3427.py
  Python/46.Goldbach's other conjecture/said3427.py
  README.md
Labels: All Correct, Resolve Conflict

#150 problem_18 done in Python
  Python/18. Maximum path sum I/ramonssarmento.py
  README.md
Labels: All Correct

#154 Create ProjectEuler3.java
  Java/3.Largest Prime Factor/ProjectEuler3.java
Labels: All Correct

#157 12 done in C
  C/12.Highly_divisible_triangular_number/prajwal-naik.c
Labels: All Correct

#158 Problem 16 done in Python3
  Python/16. Power digit sum/vrindaaa.py
Labels: All Correct

#159 Problem 20 done in Python3
  Python/20.Factorial digit sum/vrindaaa.py
Labels: All Correct

#162 Problem 13 done in Python3
  Python/13. Large sum/vrindaaa.py
Labels: All Correct

#165 problem_6 done in Java
  Java/6.Sum Square Difference/mucahidcelik.java
Labels: All Correct

#166 problem_03 done in R
  R/3. Largest Prime Factor/servindc.R
  README.md
Labels: All Correct

#161 Added Problem 27. Quadratic Primes in JAVA
  Java/27. Quadratic Primes/ritwickghosh.java
  README.md
Labels: All Correct

#160 2 done in Ruby
  README.md
  Ruby/02.Even Fibonacci numbers/24sharkS.rb
Labels: All Correct, Resolve Conflict

#170 Add 01 Multiples of 3 and 5 solution for Swift
  README.md
  Swift/1. Multiples of 3 and 5/multiplesOf3And5.swift
Labels: All Correct

#156 20. done in Kotlin
  Kotlin/20.Factorial_digit_sum/bartonstanly.kt
  README.md
Labels: All Correct

#172 problem_2 done in Java
  Java/2.Even Fibonacci numbers/mucahidcelik.java
Labels: All Correct

#178 problem_31 done in python3
  Python/31. Coin sums/kohzhixin.py
  README.md
Labels: All Correct

#173 1 done in C#
  C#/1.Multiples_of_3_and_5/arya-prof.cs
  README.md
Labels: All Correct, Re-Check-GuideLines, Resolve Conflict
